name: LinkedIn Job Scraper Node

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '5 * * * *'
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build workflow with Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

          #branch: ${{ github.ref }}

      - run: npm install
      - run: npm start

      - name: Create local changes
          run: npm start
      - name: Commit files
          run: |
            git config --local user.email "hijikeshhijal@gmail.com"
            git config --local user.name "hijal"
            git commit -m "Add changes" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
